<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateCmsFormsLiveaccountsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cms_forms_liveaccounts', function(Blueprint $table) {
            $table->increments('id');
            $table->string('user_id',50);
            $table->string('title',50);
            $table->string('first_name',50);
            $table->string('middle_name',50);
            $table->string('last_name',50);
            $table->string('gender',50);
            $table->string('date_of_birth',50);
            $table->string('fax',50);
            $table->string('tel',50);
            $table->string('office',50);
            $table->string('nationality',50);
            $table->string('id_number',50);
            $table->string('postal_code',50);
            $table->string('account_type',50);
            $table->string('base_currency_limit',50);
            $table->string('default_platform',50);
            $table->string('referring_partner',50);
            $table->string('fund_manager',50);
            $table->string('sole_joint_account',50);
            $table->string('marital_status',50);
            $table->string('resident_status',50);
            $table->string('street_and_number',50);
            $table->string('city',50);
            $table->string('main_phone',50);
            $table->string('secondary_phone',50);
            $table->string('primary_email',50);
            $table->string('secondary_email',50);
            $table->string('postal_street_and_number',50);
            $table->string('postal_post_code',50);
            $table->string('postal_city',50);
            $table->string('postal_country',50);
            $table->string('country',50);
            $table->string('financial_instrument_portfolio',50);
            $table->string('source_funds_deposited',50);
            $table->string('other_source_funds_deposited',50);
            $table->string('understand_risks',50);
            $table->string('experience_cfd',50);
            $table->string('experience_commodities',50);
            $table->string('experience_forex',50);
            $table->string('experience_futures',50);
            $table->string('experience_options',50);
            $table->string('experience_securities',50);
            $table->string('number_of_years_cfd',50);
            $table->string('number_of_years_commodities',50);
            $table->string('number_of_years_forex',50);
            $table->string('number_of_years_futures',50);
            $table->string('number_of_years_options',50);
            $table->string('number_of_years_securities',50);
            $table->string('number_of_transactions_cfd',50);
            $table->string('number_of_transactions_commodities',50);
            $table->string('number_of_transactions_forex',50);
            $table->string('number_of_transactions_futures',50);
            $table->string('number_of_transactions_options',50);
            $table->string('number_of_transactions_securities',50);
            $table->string('average_trading_cfd',50);
            $table->string('average_trading_commodities',50);
            $table->string('average_trading_forex',50);
            $table->string('average_trading_futures',50);
            $table->string('average_trading_options',50);
            $table->string('average_trading_securities',50);
            $table->string('understand_market_cfd',50);
            $table->string('understand_market_commodities',50);
            $table->string('understand_market_forex',50);
            $table->string('understand_market_futures',50);
            $table->string('understand_market_options',50);
            $table->string('understand_market_securities',50);
            $table->string('understand_market_years_cfd',50);
            $table->string('understand_market_years_commodities',50);
            $table->string('understand_market_years_forex',50);
            $table->string('understand_market_years_futures',50);
            $table->string('understand_market_years_options',50);
            $table->string('understand_market_years_securities',50);
            $table->string('first_name_joint',50);
            $table->string('second_name_joint',50);
            $table->string('last_name_joint',50);
            $table->string('account_type_joint',50);
            $table->string('title_joint',50);
            $table->string('gender_joint',50);
            $table->string('date_of_birth_joint',50);
            $table->string('fax_joint',50);
            $table->string('nationality_joint',50);
            $table->string('postal_code_joint',50);
            $table->string('base_currency_limit_joint',50);
            $table->string('default_platform_joint',50);
            $table->string('referring_partner_joint',50);
            $table->string('fund_manager_joint',50);
            $table->string('sole_joint_account_joint',50);
            $table->string('marital_status_joint',50);
            $table->string('resident_status_joint',50);
            $table->string('street_and_number_joint',50);
            $table->string('city_joint',50);
            $table->string('main_phone_joint',50);
            $table->string('secondary_phone_joint',50);
            $table->string('primary_email_joint',50);
            $table->string('secondary_email_joint',50);
            $table->string('postal_street_and_number_joint',50);
            $table->string('postal_post_code_joint',50);
            $table->string('postal_city_joint',50);
            $table->string('postal_country_joint',50);
            $table->string('country_joint',50);
            $table->string('financial_instrument_portfolio_joint',50);
            $table->string('source_funds_deposited_joint',50);
            $table->string('other_source_funds_deposited_joint',50);
            $table->string('understand_risks_joint',50);
            $table->string('experience_cfd_joint',50);
            $table->string('experience_commodities_joint',50);
            $table->string('experience_forex_joint',50);
            $table->string('experience_futures_joint',50);
            $table->string('experience_options_joint',50);
            $table->string('experience_securities_joint',50);
            $table->string('number_of_years_cfd_joint',50);
            $table->string('number_of_years_commodities_joint',50);
            $table->string('number_of_years_forex_joint',50);
            $table->string('number_of_years_futures_joint',50);
            $table->string('number_of_years_options_joint',50);
            $table->string('number_of_years_securities_joint',50);
            $table->string('number_of_transactions_cfd_joint',50);
            $table->string('number_of_transactions_commodities_joint',50);
            $table->string('number_of_transactions_forex_joint',50);
            $table->string('number_of_transactions_futures_joint',50);
            $table->string('number_of_transactions_options_joint',50);
            $table->string('number_of_transactions_securities_joint',50);
            $table->string('average_trading_cfd_joint',50);
            $table->string('average_trading_commodities_joint',50);
            $table->string('average_trading_forex_joint',50);
            $table->string('average_trading_futures_joint',50);
            $table->string('average_trading_options_joint',50);
            $table->string('average_trading_securities_joint',50);
            $table->string('understand_market_cfd_joint',50);
            $table->string('understand_market_commodities_joint',50);
            $table->string('understand_market_forex_joint',50);
            $table->string('understand_market_futures_joint',50);
            $table->string('understand_market_options_joint',50);
            $table->string('understand_market_securities_joint',50);
            $table->string('understand_market_years_cfd_joint',50);
            $table->string('understand_market_years_commodities_joint',50);
            $table->string('understand_market_years_forex_joint',50);
            $table->string('understand_market_years_futures_joint',50);
            $table->string('understand_market_years_options_joint',50);
            $table->string('understand_market_years_securities_joint',50);
            $table->string('agreem_check_1',50);
            $table->string('agreem_check_2',50);
            $table->string('agreem_check_3',50);
            $table->string('agreem_check_4',50);
            $table->string('agreem_check_5',50);
            $table->string('agreem_check_6',50);
            $table->string('agreem_check_7',50);
            $table->string('agreem_check_8',50);
            $table->string('agreem_check_9',50);
            $table->string('agreem_check_10',50);
            $table->string('agreem_check_11',50);
            $table->string('agreem_check_12',50);
            $table->string('joint_first_date',50);
            $table->string('joint_first_fullname',50);
            $table->string('joint_first_title',50);
            $table->string('joint_second_date',50);
            $table->string('joint_second_fullname',50);
            $table->string('joint_second_title',50);
            $table->string('document_id',50);
            $table->string('document_id2',50);
            $table->string('document_por',50);
            $table->string('id_type',50);
            $table->string('proof_of_residence',50);
            $table->string('pdf',50);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('cms_forms_liveaccounts');
    }
}
